### ISSUE TITLE
Request to work with your source code

### ISSUE THREAD

**Issue by peprahobedadjei** [sommaa/spray_dryer#1]
Hi @sommaa 

I’m Obed from Ireland, and I am currently working on a PHD project titled “AI-Enhanced Self-Updating Digital Twin for Optimised Spray Drying in Dairy Manufacturing.” I came across your code and found it very insightful for my project. I would love to explore the possibility of working with you and collaborating if you’re open to it. Let me know if this would be of interest to you!

Best regards,
Obed

**Comment by sommaa** [comment]
Yes! No problem let's connect on linkedin. I think you have already found it 🍸.
Andrea
